services:
  - type: web
    name: part-sales-opportunity
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: EBAY_OAUTH_SCOPES
        value: https://api.ebay.com/oauth/api_scope/buy.marketplace.insights

